builddrafts = false
languageCode = "en-us"
title = "edwardkenfox.com"
baseurl = "https://edwardkenfox.com"
theme="cocoa"
googleAnalytics = "UA-42113774-1"

[permalinks]
  fixed = ":title/"
  blog  = "blog/:slug/"

[params]
  author = "Edward Fox"
  email = "edwardkenfox@gmail.com"
  github = "//github.com/edwardkenfox"
  twitter = "//twitter.com/edwardkenfox"
