languageCode = "en-us"
title = "edwardkenfox.com"
baseURL = "https://edwardkenfox.com"
theme = "cocoa"
googleAnalytics = "UA-42113774-1"
disqusShortname = "edwadkenfox-com"

[build]
  buildDrafts = false

[permalinks]
  fixed = ":title/"
  blog  = "blog/:slug/"
  playground = "playground/:slug/"

[params]
  author = "Edward Fox"
  email = "edwardkenfox@gmail.com"
  github = "//github.com/edwardkenfox"
  twitter = "//twitter.com/edwardkenfox"
  highlightjs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = true
